//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrzeszekTransfer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrzeszekTransfer.Interface.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if port is open....
        /// </summary>
        internal static string CheckingIfPortIsOpen {
            get {
                return ResourceManager.GetString("CheckingIfPortIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not check if port is open.
        /// </summary>
        internal static string CouldNotCheckIfPortIsOpen {
            get {
                return ResourceManager.GetString("CouldNotCheckIfPortIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string DownloadLinkText {
            get {
                return ResourceManager.GetString("DownloadLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not share the file..
        /// </summary>
        internal static string FailedToMakeAvailable {
            get {
                return ResourceManager.GetString("FailedToMakeAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not share the file (file not found)..
        /// </summary>
        internal static string FailedToMakeAvailableNotFound {
            get {
                return ResourceManager.GetString("FailedToMakeAvailableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not accept incoming connections on port {0}..
        /// </summary>
        internal static string ListenerFailedAccept {
            get {
                return ResourceManager.GetString("ListenerFailedAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not listen for incoming connections on port {0}..
        /// </summary>
        internal static string ListenerFailedStart {
            get {
                return ResourceManager.GetString("ListenerFailedStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orzeszek Transfer {0} is now available..
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orzeszek Transfer.
        /// </summary>
        internal static string OrzeszekTransfer {
            get {
                return ResourceManager.GetString("OrzeszekTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.orzeszek.org/dev/transfer/.
        /// </summary>
        internal static string OrzeszekTransferUri {
            get {
                return ResourceManager.GetString("OrzeszekTransferUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string OrzeszekTransferVersion {
            get {
                return ResourceManager.GetString("OrzeszekTransferVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}:{1}/{2}/{3}.
        /// </summary>
        internal static string SharedFileUrl {
            get {
                return ResourceManager.GetString("SharedFileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}/{1}/{2}.
        /// </summary>
        internal static string SharedFileUrlWithoutPort {
            get {
                return ResourceManager.GetString("SharedFileUrlWithoutPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} B.
        /// </summary>
        internal static string SizeB {
            get {
                return ResourceManager.GetString("SizeB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} EB.
        /// </summary>
        internal static string SizeEB {
            get {
                return ResourceManager.GetString("SizeEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} GB.
        /// </summary>
        internal static string SizeGB {
            get {
                return ResourceManager.GetString("SizeGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} KB.
        /// </summary>
        internal static string SizeKB {
            get {
                return ResourceManager.GetString("SizeKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} MB.
        /// </summary>
        internal static string SizeMB {
            get {
                return ResourceManager.GetString("SizeMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} PB.
        /// </summary>
        internal static string SizePB {
            get {
                return ResourceManager.GetString("SizePB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} TB.
        /// </summary>
        internal static string SizeTB {
            get {
                return ResourceManager.GetString("SizeTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} YB.
        /// </summary>
        internal static string SizeYB {
            get {
                return ResourceManager.GetString("SizeYB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} ZB.
        /// </summary>
        internal static string SizeZB {
            get {
                return ResourceManager.GetString("SizeZB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} B/s.
        /// </summary>
        internal static string SpeedB {
            get {
                return ResourceManager.GetString("SpeedB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} EB/s.
        /// </summary>
        internal static string SpeedEB {
            get {
                return ResourceManager.GetString("SpeedEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} GB/s.
        /// </summary>
        internal static string SpeedGB {
            get {
                return ResourceManager.GetString("SpeedGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} KB/s.
        /// </summary>
        internal static string SpeedKB {
            get {
                return ResourceManager.GetString("SpeedKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} MB/s.
        /// </summary>
        internal static string SpeedMB {
            get {
                return ResourceManager.GetString("SpeedMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} PB/s.
        /// </summary>
        internal static string SpeedPB {
            get {
                return ResourceManager.GetString("SpeedPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} TB/s.
        /// </summary>
        internal static string SpeedTB {
            get {
                return ResourceManager.GetString("SpeedTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} YB/s.
        /// </summary>
        internal static string SpeedYB {
            get {
                return ResourceManager.GetString("SpeedYB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N1} ZB/s.
        /// </summary>
        internal static string SpeedZB {
            get {
                return ResourceManager.GetString("SpeedZB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete: {0:P1}.
        /// </summary>
        internal static string StatusComplete {
            get {
                return ResourceManager.GetString("StatusComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed: {0:N0}.
        /// </summary>
        internal static string StatusCompletedCount {
            get {
                return ResourceManager.GetString("StatusCompletedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size: {0}.
        /// </summary>
        internal static string StatusFileSize {
            get {
                return ResourceManager.GetString("StatusFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string StatusIdle {
            get {
                return ResourceManager.GetString("StatusIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested: {0}.
        /// </summary>
        internal static string StatusRequested {
            get {
                return ResourceManager.GetString("StatusRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested: None.
        /// </summary>
        internal static string StatusRequestedNone {
            get {
                return ResourceManager.GetString("StatusRequestedNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running: {0:N0}.
        /// </summary>
        internal static string StatusRunningCount {
            get {
                return ResourceManager.GetString("StatusRunningCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed: {0}.
        /// </summary>
        internal static string StatusSpeed {
            get {
                return ResourceManager.GetString("StatusSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed: Idle.
        /// </summary>
        internal static string StatusSpeedIdle {
            get {
                return ResourceManager.GetString("StatusSpeedIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time remaining: {0}.
        /// </summary>
        internal static string StatusTimeRemaining {
            get {
                return ResourceManager.GetString("StatusTimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time remaining: Idle.
        /// </summary>
        internal static string StatusTimeRemainingIdle {
            get {
                return ResourceManager.GetString("StatusTimeRemainingIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded: {0}.
        /// </summary>
        internal static string StatusUploaded {
            get {
                return ResourceManager.GetString("StatusUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded: None.
        /// </summary>
        internal static string StatusUploadedNone {
            get {
                return ResourceManager.GetString("StatusUploadedNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port appears to be closed.
        /// </summary>
        internal static string ThePortAppearsToBeClosed {
            get {
                return ResourceManager.GetString("ThePortAppearsToBeClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port appears to be open.
        /// </summary>
        internal static string ThePortAppearsToBeOpen {
            get {
                return ResourceManager.GetString("ThePortAppearsToBeOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:D}:{1:D2}:{2:D2}.
        /// </summary>
        internal static string TimeSpanFormat {
            get {
                return ResourceManager.GetString("TimeSpanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer of {0} failed..
        /// </summary>
        internal static string TransferFailed {
            get {
                return ResourceManager.GetString("TransferFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer of {0} failed (file has changed since it was shared)..
        /// </summary>
        internal static string TransferFailedFileMismatch {
            get {
                return ResourceManager.GetString("TransferFailedFileMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer of {0} failed (file not found)..
        /// </summary>
        internal static string TransferFailedNotFound {
            get {
                return ResourceManager.GetString("TransferFailedNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer of {0} was interrupted..
        /// </summary>
        internal static string TransferInterrupted {
            get {
                return ResourceManager.GetString("TransferInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer of {0} finished..
        /// </summary>
        internal static string TransferSuccess {
            get {
                return ResourceManager.GetString("TransferSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string TrayIconExit {
            get {
                return ResourceManager.GetString("TrayIconExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Show.
        /// </summary>
        internal static string TrayIconShow {
            get {
                return ResourceManager.GetString("TrayIconShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL copied to clipboard..
        /// </summary>
        internal static string UrlCopiedToClipboard {
            get {
                return ResourceManager.GetString("UrlCopiedToClipboard", resourceCulture);
            }
        }
    }
}
